# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "ahci" "xhci_pci" "thunderbolt" "nvme" "usb_storage" "usbhid" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/22a9f643-a324-4481-b46b-24abc1cae851";
      fsType = "ext4";
    };

  fileSystems."/boot" =
  { 
      device = "/dev/disk/by-uuid/BDBE-C36C";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
  };
  
  fileSystems."/mnt/usb" =
  { 
      device = "/dev/sda1";
      fsType = "vfat";
      options = [ "nofail" "user" "rw" "uid=1000" "gid=100" "umask=0002" ];
  };

#  fileSystems."/mnt/downloads" = 
#  {
#    device = "192.168.1.250:/volume2/downloads";
#    fsType = "nfs";
#    options = [ "nofail" "bg" ];
#  };

  fileSystems."/mnt/bjj" = 
  {
    device = "192.168.1.250:/volume2/bjj";
    fsType = "nfs";
    options = [ "nofail" "bg" ];
  };

#  fileSystems."/mnt/media" = 
#  {
#    device = "192.168.1.250:/volume2/media";
#    fsType = "nfs";
#    options = [ "nofail" "bg" ];
#  };



  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp34s0u2u1u2.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp9s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware = {
    cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
    bluetooth = {
      enable = true;
      powerOnBoot = true;
    };
    
  };
}
